[pytest]
addopts = -v --tb=short --strict-markers
markers =
    smoke: smoke tests
    auth: authorization tests
    reg: registration tests
    recovery: password recovery tests
    code: auth by code tests